@url = http://localhost:8080/posting

### [ ] Get back all posting records

GET {{url}} HTTP/1.1

### [ ] Get back one posting by their ID

GET {{url}}/5 HTTP/1.1

### [ ] Get back postings by someone's GT

GET {{url}}/player/gt_maria HTTP/1.1

### [ ] Get back postings by game ID

GET {{url}}/game/id/5 HTTP/1.1

### [ ] Get back postings by date

GET {{url}}/date/ HTTP/1.1